[phases.setup]
nixPkgs = [
  "php83",
  "php83Packages.composer",
  "libzip",
  "libpng",
  "libjpeg",
  "freetype"
]

[phases.install]
cmds = [
  "composer install --no-dev --optimize-autoloader --no-interaction"
]

[start]
cmd = "php -S 0.0.0.0:$PORT -t ."

[variables]
APP_ENV = "production"
API_URL = "https://api-spreadsheet.goodlifemicrolending.com"
